### PR TITLE
APPEALS-13122: Created models, migration, factories and updated specs

### PR DESCRIPTION
**Pull request by bvni**
Resolves [APPEALS-13122](https://vajira.max.gov/browse/APPEALS-13122)

### Description
The purpose of this Pull request is to create new table (`membership_requests`), model, factory and write tests. 

### Acceptance Criteria
- [ ] Creation of a membership request class
- [ ] Creation of membership request factory
- [ ] Creation of migration of new membership request
- [ ] The membership request database entry will need to capture the following information:
  - [ ] Request ID
  - [ ] Requestor's User ID
  - [ ] Created at Date/Time
  - [ ] Status (Assigned/Approved/Denied/Cancelled)
  - [ ] Requesting Organization ID
  - [ ] Closed by User ID (nullable)
  - [ ] Closed at Date/Time

### Testing Plan
1. Do a git pull of this branch.
2. run `rake db:migrate`
3. Open rails console and check if the model is created or not by running the following command `MembershipRequest.count` It should not error out, it should return zero if there are no records

### CODE REVIEW

File: db/migrate/20230112214407_create_membership_requests.rb [hunk 1]
```diff
@@ -0,0 +1,15 @@
+# frozen_string_literal: true
+
+class CreateMembershipRequests < ActiveRecord::Migration[5.2]
+  def change
+    create_table :membership_requests do |t|
+      t.references :user
+      t.references :organization
+      t.string :status, null: false
+      t.string :closed_by_user_id, null: true
+      t.datetime :closed_at_datetime
```
Comment (TylerBroyles) [inline db/migrate/20230112214407_create_membership_requests.rb:10]:
```suggestion
      t.datetime :closed_at
```
I don't think the _datetime is necessary

File: db/schema.rb [hunk 2]
```diff
@@ -1084,6 +1084,18 @@
...
   end
 
+  create_table "membership_requests", force: :cascade do |t|
+    t.datetime "closed_at_datetime"
+    t.string "closed_by_user_id"
+    t.datetime "created_at", null: false
+    t.bigint "organization_id"
+    t.string "status", null: false
+    t.datetime "updated_at", null: false
+    t.bigint "user_id"
```
Comment (TylerBroyles) [inline db/schema.rb:1094]: I don't know if this should be bigint or integer. It's used as both types in a lot of different tables. Might be a question we need to bring up to the whole development team.

File: db/schema.rb [hunk 3]
```diff
@@ -1084,6 +1084,18 @@
     t.index ["request_issue_id"], name: "index_legacy_issues_on_request_issue_id"
   end
 
+  create_table "membership_requests", force: :cascade do |t|
+    t.datetime "closed_at_datetime"
+    t.string "closed_by_user_id"
```
Comment (TylerBroyles) [inline db/schema.rb:1089]: This should be an integer since it's a user id association.

File: spec/models/membership_request_spec.rb [hunk 4]
```diff
@@ -0,0 +1,22 @@
+# frozen_string_literal: true
+
+describe MembershipRequest do
+  let(:membership_request) { build(:membership_request) }
```
Comment (TylerBroyles) [inline spec/models/membership_request_spec.rb:4]: I would test the object creation without the factory to verify that it works. MembershipRequest.new and then save the newly created instance variable to test how a real controller would use the object.

**Review by TylerBroyles — CHANGES_REQUESTED** [review]
First pass is good. I think we will need to account for a few more use cases and add some more rails/active record model generation syntax.

File: db/schema.rb (hunk 2 above)
Comment (bvni) [reply db/schema.rb:1094]: @TylerBroyles It automatically used bigint in the schema.rb. If you see the migration i didnt mention whether it should be int or bigint. it only has `belongs_to :user`

File: app/models/membership_request.rb [hunk 5]
```diff
@@ -0,0 +1,15 @@
+# frozen_string_literal: true
+
+class MembershipRequest < ApplicationRecord
+  belongs_to :user
```
[the remark this answers is not in the document]
Comment (bvni) [reply app/models/membership_request.rb:4]: so are we going to have 2 more columns added to the table? @TylerBroyles

File: app/models/membership_request.rb [hunk 6]
```diff
@@ -0,0 +1,15 @@
...
+  belongs_to :organization
+
+  validates :status, presence: true
```
[the remark this answers is not in the document]
Comment (bvni) [reply app/models/membership_request.rb:7]: i am confused. where did the created_by_user and created_at date fields come. do you mean closed_by_user_id and closed_at fields?

[the remark this answers is not in the document]
Comment (TylerBroyles) [reply app/models/membership_request.rb:7]: Created at comes from the rails helper method t.timestamps in the migration script. It's also present in the schema. I think it's a fine candidate for validation since there should always be a created at time. You can't really create a request without a user/organization  so those are also pretty good candidates for validation on_create.

File: app/models/membership_request.rb (hunk 5 above)
[the remark this answers is not in the document]
Comment (TylerBroyles) [reply app/models/membership_request.rb:4]: In the schema there is already a closed_by_user_id so it is present to some degree. However, it needs to be indicated by rails so you get all the necessary reflection code to use active record properly. So there probably needs to be a created_by user and a closed_by or (decision_by) user belongs to statement.

File: db/schema.rb (hunk 2 above)
Comment (TylerBroyles) [reply db/schema.rb:1094]: Interesting, that's fine. Bigint is probably more future proof and if that is what it generated then I see no problems with it. It will probably be renamed though since there are going to be two fields that are different users when the model change is made.

File: app/models/membership_request.rb (hunk 6 above)
[the remark this answers is not in the document]
Comment (bvni) [reply app/models/membership_request.rb]: created_at time gets assigned automatically when a new record is created. its a rails helper. so, i dont think we need a validation for it. it will be present no matter what if a record is present.

File: app/models/membership_request.rb [hunk 7]
```diff
@@ -0,0 +1,15 @@
...
+
+  enum status: {
+    assigned: "assigned",
+    approved: "approved",
+    denied: "denied",
+    cancelled: "cancelled"
+  }
```
[the remark this answers is not in the document]
Comment (bvni) [reply app/models/membership_request.rb:16]: made this as default in database. for some reason i kept getting error 

```
rails enum undefined method `each_with_index' for :assigned:symbol

File: app/models/membership_request.rb (hunk 5 above)
[the remark this answers is not in the document]
Comment (bvni) [reply app/models/membership_request.rb]: Addressed this.

File: spec/models/membership_request_spec.rb (hunk 4 above)
Comment (bvni) [reply spec/models/membership_request_spec.rb]: this is updated.

File: app/models/membership_request.rb (hunk 7 above)
[the remark this answers is not in the document]
Comment (TylerBroyles) [reply app/models/membership_request.rb:16]: It seems like that syntax only works in Rails 6.1+ and that's why it errors. The only way I can think to do it with a model method without that is on the before save hooks and that's not worth it. The database/schema is a fine place to do it.

**Review by TylerBroyles — CHANGES_REQUESTED** [review]
I think this covers all of our use cases now. I just have a few comments about the migration script and some validation on the status attribute. The spec test is also failing for me I'm not sure why yet. The factory bot definition also needs to be updated to reflect the new key names.

File: spec/factories/membership_request.rb [hunk 8]
```diff
@@ -0,0 +1,12 @@
+# frozen_string_literal: true
+
+FactoryBot.define do
+  factory :membership_request do
+    association :user, factory: :user
+    association :organization, factory: :organization
+
+    status { "assigned" }
+    closed_by_user_id { Faker::Name.first_name }
+    closed_at_datetime { Faker::Date.backward }
```
[the remark this answers is not in the document]
Comment (bvni) [reply spec/factories/membership_request.rb:10]: I guess we should do this, when we actually work on the decided_by task. I will just update the field names for now here.

File: spec/models/membership_request_spec.rb [hunk 9]
```diff
@@ -0,0 +1,66 @@
...
+      end
+    end
+
+    context "when requestor id is not present" do
+      let(:membership_request) { MembershipRequest.new(organization_id: organization.id) }
+
+      it "should not save to database" do
+        membership_request.valid?
+
+        expect(membership_request.errors.full_messages).to be_present
```
[the remark this answers is not in the document]
Comment (bvni) [reply spec/models/membership_request_spec.rb:62]: now the status is default, we dont even need this. i dont see this happening ever. so this is not required

File: spec/factories/membership_request.rb [hunk 10]
```diff
@@ -0,0 +1,12 @@
+# frozen_string_literal: true
+
+FactoryBot.define do
+  factory :membership_request do
+    association :user, factory: :user
+    association :organization, factory: :organization
+
+    status { "assigned" }
```
[the remark this answers is not in the document]
Comment (bvni) [reply spec/factories/membership_request.rb:8]: will update this.

File: db/schema.rb [hunk 11]
```diff
@@ -1084,6 +1084,18 @@
     t.index ["request_issue_id"], name: "index_legacy_issues_on_request_issue_id"
   end
 
+  create_table "membership_requests", force: :cascade do |t|
+    t.datetime "closed_at"
+    t.integer "closed_by"
+    t.datetime "created_at", null: false
+    t.bigint "organization_id"
+    t.integer "requested_by"
```
[the remark this answers is not in the document]
Comment (bvni) [reply db/schema.rb:1092]: done.

File: app/models/membership_request.rb [hunk 12]
```diff
@@ -0,0 +1,17 @@
+# frozen_string_literal: true
+
+class MembershipRequest < ApplicationRecord
+  belongs_to :organization
+  belongs_to :requestor, class_name: "User", foreign_key: :requested_by
+  belongs_to :decisioner, class_name: "User", foreign_key: :closed_by, optional: true
+
+  validates :organization, presence: true
+  validates :requestor, presence: true
```
[the remark this answers is not in the document]
Comment (bvni) [reply app/models/membership_request.rb:9]: the status is now defaulted to "assigned". so it wont ever be null.

File: app/models/membership_request.rb [hunk 13]
```diff
@@ -0,0 +1,17 @@
+# frozen_string_literal: true
+
+class MembershipRequest < ApplicationRecord
+  belongs_to :organization
+  belongs_to :requestor, class_name: "User", foreign_key: :requested_by
```
[the remark this answers is not in the document]
Comment (bvni) [reply app/models/membership_request.rb:5]: in that case what does the following columns are used for `requested_by and decided_by` these will have the ids of the users. unless we want to change the columns to `requested_id and decided_id`

[the remark this answers is not in the document]
Comment (TylerBroyles) [reply app/models/membership_request.rb:5]: Generally you have keys that reflect the association name. For instance, the migration script generated organization_id for the t.references organization. If the migration generated a key for requestor, it would probably be requestor_id and a bigint based on the foreign key to the user table. I generally don't like to rename foreign keys unless they are specifically different for a good reason.

If the migration script instead said t.references requestor and t.references decider then it would properly create the keys based on what is defined in the model class. If you wanted the same key names, then you could rename the assocations to requested_by and decided_by and not have to list a foreign key in the model. You can do it whatever way you want, I just prefer them to match unless there's a good reason.

File: spec/models/membership_request_spec.rb (hunk 9 above)
[the remark this answers is not in the document]
Comment (bvni) [reply spec/models/membership_request_spec.rb:62]: added this validation.

**Review by TylerBroyles — CHANGES_REQUESTED** [review]
There are still a couple of things. Mostly due to how rails implemented references in the migrations. You have to manually specify the foreign_key attribute to be true to get it to generate.

File: db/migrate/20230112214407_create_membership_requests.rb [hunk 14]
```diff
@@ -0,0 +1,17 @@
+# frozen_string_literal: true
+
+class CreateMembershipRequests < Caseflow::Migration
+  def change
+    create_table :membership_requests do |t|
+      t.references :organization, comment: "The organization that the membership request is asking to join"
+
+      t.integer :requested_by, index: true, comment: "The requestor for this membership"
```
[the remark this answers is not in the document]
Comment (bvni) [reply db/migrate/20230112214407_create_membership_requests.rb:8]: This makes sense. I always thought that we can only say `t.references` for a table that exists. Thanks for this. I am updating it.

File: db/migrate/20230126230602_create_membership_requests.rb [hunk 15]
```diff
@@ -0,0 +1,15 @@
+class CreateMembershipRequests < Caseflow::Migration
+  def change
+    create_table :membership_requests do |t|
+      t.references :organization, foreign_key: true, comment: "The organization that the membership request is asking to join"
+
+      t.references :requestor, foreign_key: { to_table: :users }, comment: "The requestor for this membership"
```
Comment (TylerBroyles) [inline db/migrate/20230126230602_create_membership_requests.rb:6]:
```suggestion
      t.references :requestor, foreign_key: { to_table: :users }, comment: "The User that is requesting access to the organization"
```

File: db/migrate/20230126230602_create_membership_requests.rb [hunk 16]
```diff
@@ -0,0 +1,15 @@
...
+      t.references :decider, foreign_key: { to_table: :users }, index: false, null: true, comment: "The user who decides the membership_request"
```
Comment (TylerBroyles) [inline db/migrate/20230126230602_create_membership_requests.rb:7]:
```suggestion
      t.references :decider, foreign_key: { to_table: :users }, index: false, null: true, comment: "The user who decides the status of the membership request"
```

File: db/migrate/20230126230602_create_membership_requests.rb [hunk 17]
```diff
@@ -0,0 +1,15 @@
...
+
+      t.datetime :decided_at, comment: "The time when the membership request was decided at"
```
Comment (TylerBroyles) [inline db/migrate/20230126230602_create_membership_requests.rb:9]:
```suggestion
      t.datetime :decided_at, comment: "The date and time when the deider user made a decision about the membership request"
```

**Review by TylerBroyles — CHANGES_REQUESTED** [review]
Just a couple of comment changes to clarify some of the meaning of the database columns.

**Review by TylerBroyles — DISMISSED** [review]
Looks good to me. Great job!

**Review by ajspotts — APPROVED** [review]
